### ISSUE TITLE
Local time

### ISSUE THREAD

**Issue by QuantumNightmare** [MindscapeHQ/raygun4ruby#10] opened 2013-09-04 05:40 UTC
To be consistent with the other providers, within the "details" section of the payload, there should be an "environment" section containing a "utcOffset" value which is the number of hours from UTC to the timezone on the end users machine - if possible.

**Comment by stevehanson** [comment] 2016-02-03 22:27
This would be awesome. All my errors are showing in UTC on Raygun.

**Comment by CmdrKeen** [comment] 2016-02-03 22:46
@stevehanson This is by design. You can set your timezone on your profile :+1: This is a per-user setting so if you have team members around the globe you should be seeing them in local time that way (note: We did look at using the browser offset, but found often this was not accurate).

**Comment by stevehanson** [comment] 2016-02-04 03:41
@CmdrKeen perfect! I see it now. I had looked before but hadn't seen the user options on the top right. Thanks for the quick reply!

**Comment by nikz** [comment] 2016-02-04 11:20
Closing this issue as I think It's been resolved?

**Comment by UberMouse** [comment] 2017-03-15 21:19
Re-opening as this doesn't appear to be sent in the payload

**Closed** 2017-03-15 22:44 UTC
Labels: enhancement
